providers:
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

ports:
  web:
    port: 8000
    exposedPort: 80
  websecure:
    port: 8443
    exposedPort: 443

service:
  type: LoadBalancer

rbac:
  enabled: true

serviceAccount:
  create: true
  name: traefik

additionalArguments:
  - "--entrypoints.web.address=:8000"
  - "--entrypoints.websecure.address=:8443"

  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

  - "--providers.kubernetesingress=true"

  - "--certificatesresolvers.letsencrypt.acme.email=jakob.kampmann@goava.ai"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

persistence:
  enabled: true
  path: /data
  size: 128Mi

ingressRoute:
  dashboard:
    enabled: true

logs:
  general:
    level: INFO
