# Default values for miniapp.

replicaCount: 2

image:
  repository: ghcr.io/jakobulus123/miniapp
  pullPolicy: IfNotPresent
  tag: "6445eabc66585128a1d8ee187bbc01a80b52bd6f"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
