# Default values for miniapp.

replicaCount: 2
image:
  repository: ghcr.io/jakobulus123/miniapp
  pullPolicy: IfNotPresent
  tag: "8b12dd9ee091170ae9a5224fc2bfbd79cc9443de"
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
