apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.3.11  # Eine stabile Version
    helm:
      values: |
        server:
          extraArgs:
            - --insecure
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hostname: jakob-argocd.goava.ai
            tls:
              - hosts:
                  - jakob-argocd.goava.ai
                secretName: argocd-server-tls
        networkPolicies:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

