argo-cd:
  server:
    extraArgs:
      
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hostname: jakob-argocd.goava.ai
      tls: true
      secretName: argocd-server-tls
  
  # Das hier ist extrem wichtig, damit Traefik nicht blockiert wird!
  networkPolicies:
    enabled: false
