apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-bootstrap   # ❗ NICHT argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.51.6

    helm:
      releaseName: argocd   # bleibt so!
      values: |
        global:
          nameOverride: argocd
          fullnameOverride: argocd

        server:
          extraArgs:
            - --insecure

          service:
            type: ClusterIP

        configs:
          params:
            server.insecure: true

          cm:
            url: https://jakob-argocd.goava.ai

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd   # korrekt für Argo selbst

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
