apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:Jakobulus123/K8s-Helm.git
      targetRevision: HEAD
      path: charts/miniapp
    - repoURL: git@github.com:Jakobulus123/K8s-Helm.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: miniapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
