apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.3.11
    helm:
      values: |
        fullnameOverride: "argocd"
        
        server:
          extraArgs:
            - --insecure
          # Hier binden wir deinen Ingress fest in Helm ein:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/service.serversscheme: "http"
            hosts:
              - jakob-argocd.goava.ai
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - jakob-argocd.goava.ai

        global:
          additionalLabels:
            app.kubernetes.io/instance: argocd
            
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: argocd-initial-admin-secret
      jsonPointers:
        - /data
