apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: quay.io/argoproj/argocd:v2.11.7 # Exakt die Version aus deinem Cluster
        env:
        - name: ARGOCD_SERVER_INSECURE
          value: "true" # Damit er auf 8080 ohne TLS antwortet
        ports:
        - containerPort: 8080
