apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-configuration
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Jakobulus123/K8s-Helm.git
    targetRevision: HEAD
    path: ClusterManager/argocd-chart
    helm:
      values: |
        argo-cd:
          server:
            insecure: true
            extraArgs:
              - --insecure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
